dist: bionic
language: python
python: [3.8]
git:
  depth: false

stages:
  - name: test
  - name: publish
    if: tag IS present # OR ( branch IN (master) AND type IN (push) )

install:
  - |-
      setup_helm () {
          echo "setup helm ${HELM_VERSION}"
          curl -sf https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | DESIRED_VERSION=${HELM_VERSION} bash
      }
      setup_k3s () {
          echo "setup k3s ${K3S_VERSION}"
          # https://rancher.com/docs/k3s/latest/en/installation/install-options/how-to-flags/
          curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${K3S_VERSION} sh -s - \
              --write-kubeconfig-mode=644 \
              --disable traefik \
              --disable metrics-server \
              --disable local-storage \
              --disable-network-policy
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      }

# https://github.com/rancher/k3s/releases
# https://github.com/helm/helm/releases
env:
  - K3S_VERSION=v1.18.2+k3s1 HELM_VERSION=v3.2.1

jobs:
  include:
    - stage: test
      script:
        - setup_k3s
        - setup_helm
        - helm install pebble ./pebble --wait --timeout 60s --values ci/ci-values.yaml
        - helm test pebble
      after_success:
        - kubectl get all --all-namespaces
      after_failure:
        - kubectl get all --all-namespaces
        - kubectl logs pebble-test --all-containers
        - kubectl logs pebble-coredns-test --all-containers
    - stage: publish
      script:
        - pip install chartpress
        - setup_helm
        - ./ci/publish
