{{- define "pebble.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pebble.fullname" . }}
  labels:
    {{- include "pebble.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pebble.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pebble.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/configmap: {{ include "pebble.configmap" . | fromYaml | merge .Values.pebble.merge.configmap | toYaml | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 1

      volumes:
        - name: pebble-config-and-tls-root
          configMap:
            name: {{ include "pebble.fullname" . }}
        - name: pebble-temp-tls-leaf
          emptyDir: {}

      initContainers:
        - name: pebble-tls-leaf-creation
          image: twalter/minica:latest
          volumeMounts:
            - name: pebble-config-and-tls-root
              mountPath: /input
            # The Docker image's WORKDIR is /output, and minica will create a
            # folder like the first domain name (localhost) and put cert.pem and
            # key.pem into it.
            - name: pebble-temp-tls-leaf
              mountPath: /output/localhost
          command:
            # Avoid "open localhost/key.pem: file exists" as happen if the
            # container restarts for some reason.
            - sh
            - -c
            - >
                [ -e localhost/key.pem ] || exec
                minica
                -ca-cert /input/root-cert.pem
                -ca-key /input/root-key.pem
                -domains {{ include "pebble.domains" . | quote }}
                -ip-addresses 127.0.0.1

      containers:
        # Pebble is the acme server, but also expose a REST API on the
        # management port providing access to the certificates signing the acme
        # requests etc.
        - name: pebble
          image: "{{ .Values.pebble.image.repository }}:{{ .Values.pebble.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: pebble-config-and-tls-root
              subPath: pebble-config.json
              mountPath: /etc/pebble/pebble-config.json
            - name: pebble-temp-tls-leaf
              mountPath: /etc/pebble/temp-tls-leaf
          command:
            - pebble
            - -config
            - /etc/pebble/pebble-config.json
            {{- if .Values.coredns.enabled }}
            - -dnsserver 
            - {{ printf "$(%s_COREDNS_SERVICE_HOST):53" (include "pebble.fullname" .) | upper | replace "-" "_" }}
            {{- end }}
          ports:
            - name: acme
              containerPort: 8443
            - name: acme-mgmt
              containerPort: 8080
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            {{- with .Values.pebble.env }}
            {{- . | toYaml | nindent 12 }}
            {{- end }}
          readinessProbe:
            # The goal of this readiness probe are:
            # - to not clutter logs
            # - react quickly (<0.2s) on ready
            # - react decently (<2s) on not ready
            timeoutSeconds: 60
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            exec:
              command:
                - sh
                - -c
                - |
                    if [ -e /ready-signal ]
                    then
                        n=0
                        while [ $n -lt 25 ]
                        do
                            if [ "$(netstat -tl | grep 8443)" = "" ]
                            then
                                rm /ready-signal
                                exit 1
                            fi
                            sleep 2s
                            n=$((n+1))
                        done
                        exit 0
                    else
                        n=0
                        while [ $n -lt 250 ]
                        do
                            if [ "$(netstat -tl | grep 8443)" != "" ]
                            then
                                touch /ready-signal
                                exit 0
                            fi
                            sleep 0.2s
                            n=$((n+1))
                        done
                        exit 1
                    fi
{{- end }}

{{- include "pebble.deployment" . | fromYaml | merge .Values.pebble.merge.deployment | toYaml }}
